# Generated by Django 3.0.5 on 2020-05-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Popularity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='selesNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
