# Generated by Django 3.0.5 on 2020-05-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_auto_20200511_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='Popularity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='selesNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(),
        ),
    ]
