# Generated by Django 3.0.5 on 2020-05-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_auto_20200511_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='commoditie',
            name='Popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commoditie',
            name='SelesNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commoditie',
            name='Views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commoditie',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
