# Generated by Django 3.0.5 on 2020-05-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_auto_20200513_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='selesNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
